name: smartpeople_client
description: Scientific Social Network
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '2.0.0-beta.17'
  browser: '^0.10.0'
  fp: '^0.4.3'
  http: '^0.11.3+7'
  dart_to_js_script_rewriter: '^1.0.1'
  shadow_dom: any
  angular2_rbi: ^0.0.9
  smartpeople_shared:
    path: '../shared'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  angular2_testing: '^2.0.0-beta.17'
  mockito: '^0.11.0'
  postcss_transformer:
    path: transformers/postcss
#  postcss_transformer: '^0.1.1'
  quiver: '^0.22.0'
transformers:
- postcss_transformer:
    executable: ./node_modules/postcss-cli/bin/postcss
    arguments:
    - local-plugins: ''
    - use: autoprefixer
    - autoprefixer.browsers: Firefox 47, Safari 9, Chrome 52, IE 11
    - use: postcss-nesting
    - use: postcss-fixes
    - use: postcss-flexbugs-fixes
    - use: postcss-sort-style-rules
    - use: cssnano
#    - use: postcss-font-magician // Will be used later
#    - use: postcss-assets // Will be used later
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

