language: dart
dart:
  - dev
  - stable
sudo: false
install:
  - travis_retry pub get
  - travis_retry nvm install node
  - travis_retry npm install

before_script:
  - chmod +x tool/travis.sh

script:
  - tool/travis.sh