language: dart
dart:
  - stable
before_install:
  - export DISPLAY=:99.0
install:
  - travis_retry pub get
  - travis_retry nvm install node
  - travis_retry npm install
before_script:
  - chmod +x scripts/*.sh
  - scripts/build/install.sh
script:
  - scripts/build/analyze.sh
  - scripts/build/lint.sh
  - scripts/build/build.sh
  - scripts/build/tests.sh