const SAVE_EMAIL = 'SAVE_EMAIL';

const ERROR_BAD_REQUEST = 'ERROR_BAD_REQUEST';
const ERROR_REMOVE_BAD_REQUEST = 'ERROR_REMOVE_BAD_REQUEST';
const ERROR_FORBIDDEN = 'ERROR_FORBIDDEN';
const ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED';
const ERROR_REMOVE_UNAUTHORIZED = 'ERROR_REMOVE_UNAUTHORIZED';
const ERROR_NOT_FOUND = 'ERROR_NOT_FOUND';
const ERROR_REMOVE_NOT_FOUND = 'ERROR_REMOVE_NOT_FOUND';
const ERROR_INTERNAL_SERVER = 'ERROR_INTERNAL_SERVER';
const ERROR_REMOVE_INTERNAL_SERVER = 'ERROR_REMOVE_INTERNAL_SERVER';
const ERROR_REMOVE_FORBIDDEN = 'ERROR_REMOVE_FORBIDDEN';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN_CHECK = 'LOGIN_CHECK';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

const RESTORE_ACCESS_GET_CODE = 'RESTORE_ACCESS_GET_CODE';
const RESTORE_ACCESS_APPLY_CODE = 'RESTORE_ACCESS_APPLY_CODE';
const RESTORE_ACCESS_CHANGE_PASSWORD = 'RESTORE_ACCESS_CHANGE_PASSWORD';
const RESTORE_ACCESS_CLEAR_DATA = 'RESTORE_ACCESS_CLEAR_DATA';

const SIGN_UP_SAVE_PASSWORD = 'SIGN_UP_SAVE_PASSWORD';
const SIGN_UP_SEND_DATA = 'SIGN_UP_SEND_DATA';
const SIGN_UP_RESEND_CONFIRM_CODE = 'SIGN_UP_RESEND_CONFIRM_CODE';
const SIGN_UP_APPLY_CONFIRMATION_CODE = 'SIGN_UP_APPLY_CONFIRMATION_CODE';
const SIGN_UP_CLEAR_DATA = 'SIGN_UP_CLEAR_DATA';
