name: smartpeople_server
description: Scientific Social Network
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  shelf: '^0.6.5+2'
  shelf_static: '0.2.4'
  shelf_proxy: '0.1.0+4'
  redstone: '^0.6.1'
  postgresql: '0.3.3'
  uuid: '0.5.1'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  angular2_testing: '^2.0.0-beta.17'
  mockito: '^0.11.0'
  quiver: '^0.22.0'
