name: SmartPeopleUI
description: Scientific Social Network
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.10
  browser: ^0.10.0
  angular2_material: "^2.0.0-beta.10"
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter